container_build:
  overrides:
    version_command: mvn help:evaluate -Dexpression=project.version -q -DforceStdout
    java:
      classifier: shaded
      group: com.apixio.PROJECTNAME
      additional_jars:
        bc-fips:
          group: org.bouncycastle
          version: "1.0.2.1"
          enabled: true
        bcprov-jdk15on:
          group: org.bouncycastle
          version: "1.68"
          enabled: true
